project:
  type: website
  output-dir: _docs

website:
  title: "FastAPI Webapp Template"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: docs/architecture.qmd
        text: Architecture
      - href: docs/authentication.qmd
        text: Authentication
      - href: docs/installation.qmd
        text: Installation
      - href: docs/customization.qmd
        text: Customization
      - href: docs/deployment.qmd
        text: Deployment
      - href: docs/contributing.qmd
        text: Contributing
    right:
      - icon: github
        href: https://github.com/promptly-technologies-llc/fastapi-jinja2-postgres-webapp
  page-footer:
    left: "Copyright 2024, Promptly Technologies, LLC. MIT License."
    right:
      - icon: github
        href: https://github.com/promptly-technologies-llc/fastapi-jinja2-postgres-webapp
format:
  html:
    theme: cosmo
    css: docs/static/styles.css
    toc: true
