[tool.poetry]
name = "fastapi-jinja2-postgres-webapp"
version = "0.1.0"
description = "A template webapp with a pure-Python FastAPI backend, frontend templating with Jinja2, and a Postgres database to power user auth"
authors = ["Christopher Carroll Smith <chriscarrollsmith@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
sqlmodel = "^0.0.22"
mypy = "^1.11.2"
fastapi = "^0.114.1"
pyjwt = "^2.9.0"
jinja2 = "^3.1.4"
uvicorn = "^0.30.6"
psycopg2 = "^2.9.9"
pydantic = {extras = ["email"], version = "^2.9.1"}
python-multipart = "^0.0.9"
python-dotenv = "^1.0.1"
resend = "^2.4.0"
bcrypt = "^4.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
