on:
    workflow_dispatch:
    push:
      branches: main

  name: Quarto Publish
  
  jobs:
    build-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v4 
  
        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
  
        - name: Render and Publish 
          uses: quarto-dev/quarto-actions/publish@v2
          with:
            target: quarto-pub
            QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}
        
#        - name: Traditionally Render & Publish
#          run: |
#          quarto publish
#          quarto render index.qmd --output-dir . --output README.md --to gfm
#          unlink index.html  # Can skip this step if we add/commit/push only the README rather than all changed files
