name: Update Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'index.qmd'
      - '.github/workflows/update-docs.yml'
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Documentation
        run: |
          # Publish Quarto documentation
          quarto publish --no-prompt --no-browser
          
          # Render README in GitHub Flavored Markdown
          quarto render index.qmd --output-dir . --output README.md --to gfm
          
          # Remove index.html if it exists
          rm -f index.html

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Stage only specific files
          git add README.md
          
          # Only commit if there are changes
          git diff --staged --quiet || git commit -m "docs: Update README.md via automated workflow"
          
          # Push changes
          git push

      # Optional step for generating additional documentation files
      - name: Generate Additional Documentation
        if: false  # Disabled by default - enable when needed
        run: |
          # Example: Generate .txt version
          quarto render index.qmd --output-dir . --output rules.txt --to plain
          
          # Example: Generate .cursorrules version
          quarto render index.qmd --output-dir . --output rules.cursorrules --to plain
          
          # Commit and push additional files
          git add rules.txt rules.cursorrules
          git diff --staged --quiet || git commit -m "docs: Update additional documentation files"
          git push
